
workflows:
  ios-workflow:
    name: Build vxkit
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Nettoyage et Configuration iOS
        script: |
          rm -rf ios
          flutter create --platforms ios .
          
          # FORCE iOS VERSION 14.0 (Correction de l'erreur WebView)
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [^;]*;/IPHONEOS_DEPLOYMENT_TARGET = 14.0;/g' ios/Runner.xcodeproj/project.pbxproj
          echo "platform :ios, '14.0'" > ios/Podfile
          
          flutter clean
          flutter packages pub get
          cd ios && pod install && cd ..
      - name: Compilation brute iOS
        script: | 
          flutter build ios --release --no-codesign
      - name: Création du package IPA
        script: | 
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r $CM_BUILD_DIR/vxkit.ipa Payload
    artifacts:
      - "*.ipa"
