
workflows:
  ios-workflow:
    name: Build vxkit
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Nettoyage et Régénération du projet
        script: |
          # 1. On supprime l'ancien dossier ios s'il existe
          rm -rf ios
          
          # 2. On recrée un projet iOS vierge et propre
          flutter create --platforms ios .
          
          # 3. On nettoie les caches Flutter
          flutter clean
          
          # 4. On récupère les packages (dont webview_flutter)
          flutter packages pub get
          
      - name: Génération automatique et installation de CocoaPods
        script: |
          # Cette commande force Flutter à générer les fichiers de configuration iOS natifs (dont le Podfile)
          flutter build ios --config-only
          
          # On entre dans le dossier ios généré, on installe les pods pour la WebView, puis on ressort
          cd ios
          pod install
          cd ..
          
      - name: Compilation brute iOS
        script: | 
          # Maintenant que CocoaPods est configuré avec la WebView, on compile sans signature
          flutter build ios --release --no-codesign
          
      - name: Création du package IPA pour Sideloadly
        script: | 
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r $CM_BUILD_DIR/vxkit.ipa Payload
    artifacts:
      - "*.ipa"
